name: Unit Tests

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    uses: RedHatInsights/processing-tools/.github/workflows/pytests.yaml@master
    with:
      cov_branch: true
    secrets: inherit
